CRITICAL - 2024-05-06 05:54:51 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\BooksModel"
in SYSTEMPATH\Model.php on line 766.
 1 SYSTEMPATH\Model.php(766): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\BooksModel')
 2 SYSTEMPATH\BaseModel.php(783): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 4 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 5 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-06 05:58:24 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\BooksModel"
in SYSTEMPATH\Model.php on line 766.
 1 SYSTEMPATH\Model.php(766): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\BooksModel')
 2 SYSTEMPATH\BaseModel.php(783): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 4 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 5 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-06 05:58:56 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\BooksModel"
in SYSTEMPATH\Model.php on line 766.
 1 SYSTEMPATH\Model.php(766): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\BooksModel')
 2 SYSTEMPATH\BaseModel.php(783): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 4 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 5 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-06 06:01:52 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(51): CodeIgniter\BaseModel->save(Array)
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#14 {main}
CRITICAL - 2024-05-06 06:01:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-06 06:01:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:01:52\', \'2024-05-06 06:01:52\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:01:52\', \'2024-05-06 06:01:52\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-06 06:01:52 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:01:52\', \'2024-05-06 06:01:52\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:01:52\', \'2024-05-06 06:01:52\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:01:52\', \'2024-05-06 06:01:52\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-06 06:02:06 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(51): CodeIgniter\BaseModel->save(Array)
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#14 {main}
CRITICAL - 2024-05-06 06:02:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-06 06:02:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:02:06\', \'2024-05-06 06:02:06\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:02:06\', \'2024-05-06 06:02:06\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-06 06:02:06 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:02:06\', \'2024-05-06 06:02:06\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:02:06\', \'2024-05-06 06:02:06\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 06:02:06\', \'2024-05-06 06:02:06\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(51): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
INFO - 2024-05-06 06:03:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 06:05:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 06:06:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 06:07:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-06 06:08:13 --> TypeError: url_title(): Argument #1 ($str) must be of type string, null given, called in D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php on line 50
in SYSTEMPATH\Helpers\url_helper.php on line 425.
 1 APPPATH\Controllers\Books.php(50): url_title(null, '-', true)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
INFO - 2024-05-06 06:10:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 06:11:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 06:53:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:26:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:38:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:41:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:41:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:47:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:51:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:52:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:53:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:54:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:57:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 07:57:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:06:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:06:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:09:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-06 08:09:59 --> ErrorException: Undefined property: App\Controllers\Books::$BooksModel
in APPPATH\Controllers\Books.php on line 51.
 1 APPPATH\Controllers\Books.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Books::$BooksModel', 'D:\\cahya2\\pemweb\\pertemuan-4\\app\\Controllers\\Books.php', 51)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
INFO - 2024-05-06 08:10:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:10:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:11:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:11:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:11:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:12:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:13:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:13:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:13:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:14:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:14:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:14:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:14:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:14:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:15:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 08:32:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:06:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:06:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:06:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:06:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:07:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:07:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:08:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-06 09:12:07 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-06 09:12:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-06 09:12:23 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-06 09:12:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-06 09:12:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-06 09:12:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
INFO - 2024-05-06 09:15:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:15:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:15:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:21:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:21:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:21:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 09:21:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:26:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:27:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:27:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:27:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:33:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:33:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:33:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:33:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:58:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:58:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 10:59:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 11:00:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-06 15:40:21 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-06 15:40:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
INFO - 2024-05-06 15:40:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 15:41:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-06 15:47:01 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Database\MySQLi\Connection.php on line 307.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-05-06 15:47:05 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(56): CodeIgniter\BaseModel->save(Array)
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(56): CodeIgniter\BaseModel->save(Array)
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}
CRITICAL - 2024-05-06 15:47:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(56): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
INFO - 2024-05-06 15:51:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-06 16:07:18 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Database\MySQLi\Connection.php on line 307.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-05-06 16:07:23 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-06 16:07:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-06 16:16:58 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-06 16:16:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(20): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
INFO - 2024-05-06 16:17:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:17:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:17:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:17:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:17:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:17:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:17:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:22:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:22:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 16:22:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
